name: Balena Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl jq

      - name: Download Balena CLI
        run: |
          curl -sL "https://github.com/balena-io/balena-cli/releases/download/v20.2.3/balena-cli-v20.2.3-linux-x64-standalone.zip" -o balena-cli.zip
          unzip balena-cli.zip
          sudo mv balena-cli/balena /usr/local/bin/balena
          balena login --token ${{ secrets.BALENA_API_KEY }}

      - name: Balena Push
        run: |
          balena push sun_day_carwash/balena-tailscale
